name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: List Build Artifacts
        run: ls -R dist

  deploy_job:
    if: github.event_name == 'push'
    needs: build_job
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Deploy Directory
        run: ls -R

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_FIELD_0356FC40F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist" #/helloworld-cicd-github-actions"  # Make sure this matches your build output directory
